[package]
name = "libfiber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
# 从c/c++头文件自动生成rust
bindgen = "0.59.2"
cc = "1.0.73"
rustversion = "1.0.6"